set(_AMENT_PACKAGE_NAME "path_planning_server")
set(path_planning_server_VERSION "0.0.1")
set(path_planning_server_MAINTAINER "Chien-Ming Lin <ChienMing.Lin@itri.org.tw>")
set(path_planning_server_BUILD_DEPENDS "rclcpp" "rclcpp_action" "universal_interface")
set(path_planning_server_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(path_planning_server_BUILD_EXPORT_DEPENDS "rclcpp" "rclcpp_action" "universal_interface")
set(path_planning_server_BUILDTOOL_EXPORT_DEPENDS )
set(path_planning_server_EXEC_DEPENDS "rosidl_default_runtime" "rclcpp" "rclcpp_action" "universal_interface")
set(path_planning_server_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(path_planning_server_GROUP_DEPENDS )
set(path_planning_server_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(path_planning_server_DEPRECATED "")
set(path_planning_server_EXPORT_TAGS)
list(APPEND path_planning_server_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
